---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.nscale.com
  resources:
  - directories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.nscale.com
  resources:
  - directories/finalizers
  verbs:
  - update
- apiGroups:
  - openldap.nscale.com
  resources:
  - directories/status
  verbs:
  - get
  - patch
  - update
